{{- if include "orbitron.needsGeneratedSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "orbitron.fullname" .) }}
  labels:
    {{- include "orbitron.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.oidc.clientSecret }}
  oidc-client-secret: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
  {{- if .Values.env.tls.caBundle }}
  ca-bundle.crt: |
    {{- .Values.env.tls.caBundle | nindent 4 }}
  {{- end }}
{{- end }}